("Formate", ["Sodium Formate", "Formic Acid"])
("Acetate", ["Sodium Acetate", "Acetic Acid"])
("Citrate", ["Sodium Citrate", "Citric Acid"])
("Phosphate", ["Sodium Phosphate Monobasic", "Sodium Phosphate Dibasic"])
("MES", ["Sodium MES", "MES Acid"])
("Bis-Tris", ["Bis-Tris Base", "Bis-Tris Chloride"])
("Bis-Tris-Propane", ["Bis-Tris-Propane Base", "Hydrochloric Acid"])
("Tris", ["Tris Base", "Tris Chloride"])
("Trolamine", ["Trolamine Base", "Trolamine Chloride"])
("Histidine", ["Histidine Base", "Histidine Chloride"])
("Arginine", ["Arginine Base", "Arginine Chloride"])
("Glutamate", ["Sodium Glutamate", "Glutamic Acid"])
("Aspartate", ["Sodium Aspartate", "Aspartic Acid"])
("Histidine-Acetate", ["Histidine Base", "Acetic Acid"])
("Tris-Acetate", ["Tris Base", "Acetic Acid"])
("Tris-Formate", ["Tris Base", "Formic Acid"])
("Trolamine-Formate", ["Trolamine Base", "Formic Acid"])
("Bis-Tris-Acetate", ["Bis-Tris Base", "Acetic Acid"])