steps:
  # Install the dependencies
  - name: gcr.io/cloud-builders/npm
    dir: 'om-buffer-expert'
    args:
      - 'install'
  
  # Build the Angular app
  - name: gcr.io/cloud-builders/npm
    dir: 'om-buffer-expert'
    args:
      - 'run'
      - 'build'
      - '--configuration'
      - 'production'

  # Install firebase-tools globally
  - name: gcr.io/cloud-builders/npm
    args:
      - 'install'
      - '-g'
      - 'firebase-tools'
  
  # Deploy to Firebase
  - name: gcr.io/cloud-builders/firebase
    dir: 'om-buffer-expert/dist' # Assuming your dist directory is inside ombuffer-expert; adjust if needed
    args:
      - 'deploy'
      - '--token'
      - '1//01JveM_mCfZTbCgYIARAAGAESNwF-L9IrCVcWY40PLdjLdqZTXKSmJXG3DsRnt4cltkFTmJgiVuwwGM0zgoNDmoGBJtIosf66qRk'
      - '--project'
      - 'buffer-designer'
