steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'om-buffer-expert'

  # Build the Angular project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--configuration', 'production']
    dir: 'om-buffer-expert'

  # Deploy to Firebase
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', 'firebase-tools']
  
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'firebase'
    args: ['deploy', '--token', "1//01uI_DrICCSmdCgYIARAAGAESNwF-L9IrqYyR7PynynVERvNwBiqVqpC4u149nP86jIZDjMVu7V-cDZXSQvOphjMUGTIAvFbG4Rw", '--project', 'buffer-designer']
    dir: 'om-buffer-expert'

