steps:
  - name: gcr.io/cloud-builders/npm
    args:
      - install
    dir: om-buffer-expert

  - name: gcr.io/cloud-builders/npm
    args:
      - run
      - build
      - '--configuration production'
    dir: om-buffer-expert
  
  # Build our custom Firebase docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/buffer-designer/firebase-deploy', './firebase_deploy']

  # Use the custom Firebase docker image to deploy
  - name: 'gcr.io/buffer-designer/firebase-deploy'
    args:
      - deploy
      - '--token'
      - '1//01JveM_mCfZTbCgYIARAAGAESNwF-L9IrCVcWY40PLdjLdqZTXKSmJXG3DsRnt4cltkFTmJgiVuwwGM0zgoNDmoGBJtIosf66qRk'
      - '--project'
      - buffer-designer
    dir: om-buffer-expert
