[package]
name = "rust-buffer-om"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = "0.2"
nalgebra = "0.29"
ndarray = "0.15.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"